### ISSUE TITLE
issue typeError

### ISSUE THREAD

**Issue by blade3** [AlexEne/CCrush-Bot#2] opened 2015-11-19 17:28 UTC
I got this stacktrace.

I have output the value and it is (32,32) for "self.downscale_res".

any idea?

(I have edit some code like print "...." to print("....") because i have an error if I use your code without.

Also, i'm on python 3.5. 

Thank you!

```
Traceback (most recent call last):
  File "C:/Users/project/CCrush-Bot-master/main.py", line 172, in <module>
    main()
  File "C:/Users/project/CCrush-Bot-master/main.py", line 159, in main
    board_img = grab_board()
  File "C:/Users/meyoo/project/CCrush-Bot-master/main.py", line 104, in grab_board
    game_board[y][x] = recognizer.predict(cell)
  File "C:\Users\meyoo\project\CCrush-Bot-master\sklearn_decoder.py", line 78, in predict
    resized_img = img.resize(self.downscale_res, Image.BILINEAR)
  File "C:\Users\meyoo\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\Image.py", line 1517, in resize
    self.load()
  File "C:\Users\meyoo\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\Image.py", line 1951, in load
    self.im = self.im.crop(self.__crop)
TypeError: integer argument expected, got float
Process finished with exit code 1
```

**Comment by blade3** [comment] 2015-11-19 18:55
TO help for debug, I add some print:

```
In predict
(32, 32)
in Image.py - resize :
(32, 32)
in image.py - load :
(0.0, 0.0, 71.33333333333333, 63.55555555555556)
```

Maybe its not the path it create error but I got stack and the output after

**Comment by AlexEne** [comment] 2015-11-20 08:14
Hi,

The problem is that this was made for python 2.7 :(.  That is why you got print( ) issues and most likely this is why you are getting the type error too.
I will close this for now since python 3 is not supported / tested.
Feel free to reopen it if it also happens on python 2.7.

I should have made a requirements.txt to specify this and all the libs needed, but at the time I wrote this did not know about that.

Cheers!

**Closed as completed by AlexEne** 2015-11-20 08:14 UTC

**Comment by AlexEne** [comment] 2015-11-20 08:19
I updated the readme and I specified the python version and libraries needed.
